name: Ansible Tests

on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Check out code
          uses: actions/checkout@v1
          with:
            path: ansible_collections/launchdarkly_labs/collection
        - name: Lint code
          run: |
            pip install black
            black . --check
        - name: Inject Keys
          run: |
            find . -type f -name "*.yml" -exec sed -i "s/__CHANGE_KEY/${LAUNCHDARKLY_ACCESS_TOKEN}/g" {} +
            find . -type f -name "*.yml" -exec sed -i "s/__CHANGE_DEST_KEY/${LAUNCHDARKLY_DEST_ACCESS_TOKEN}/g" {} +
            find . -type f -name "*.yml" -exec sed -i "s/__CHANGE_SDK_KEY/${LAUNCHDARKLY_SDK_KEY}/g" {} +
          env:
            LAUNCHDARKLY_ACCESS_TOKEN: ${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
            LAUNCHDARKLY_DEST_ACCESS_TOKEN: ${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
            LAUNCHDARKLY_SDK_KEY: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
        - name: Copy vars file
          run: |
            find tests/integration/targets -type d -maxdepth 1 -exec cp tests/integration/test_vars_sample.yml {}/vars.yml \;
        - name: Install Requirements
          run: pip install -r requirements.txt --disable-pip-version-check
        - name: Run integration tests
          run: ansible-test integration --docker centos7 -v --color --retry-on-error --requirements
